# Generated by Django 6.0.2 on 2026-03-03 17:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('cpu_usage', models.FloatField(help_text='CPU Usage Percentage')),
                ('ram_usage', models.FloatField(help_text='RAM Usage Percentage')),
                ('disk_io', models.FloatField(blank=True, help_text='Disk I/O Wait Percentage', null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_data', to='accounts.company')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='monitoring.server')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['company', 'server', 'timestamp'], name='telemetry_m_company_9aec1f_idx'), models.Index(fields=['server', 'timestamp'], name='telemetry_m_server__edd1e2_idx')],
            },
        ),
        migrations.CreateModel(
            name='MetricRollup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, help_text='Truncated to the hour')),
                ('avg_cpu', models.FloatField()),
                ('avg_ram', models.FloatField()),
                ('avg_disk_io', models.FloatField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_data', to='accounts.company')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollups', to='monitoring.server')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['company', 'server', 'timestamp'], name='telemetry_m_company_3533a5_idx')],
                'unique_together': {('server', 'timestamp')},
            },
        ),
    ]
