# Generated by Django 6.0.2 on 2026-03-03 17:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('os_info', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_ping', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_data', to='accounts.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServerAlertState',
            fields=[
                ('server', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='alert_state', serialize=False, to='monitoring.server')),
                ('consecutive_healthy_count', models.PositiveIntegerField(default=0)),
                ('current_cooldown_tier', models.PositiveIntegerField(default=0, help_text='0=No active alert. 1-6=Escalating tiers.')),
                ('last_alert_sent_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_data', to='accounts.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(choices=[('cpu', 'CPU Usage (%)'), ('ram', 'RAM Usage (%)'), ('disk', 'Disk I/O Wait')], max_length=10)),
                ('threshold_value', models.FloatField(help_text='The ceiling value that triggers the alert (e.g., 90.0 for 90%).')),
                ('duration_minutes', models.PositiveIntegerField(default=5, help_text='Sustain duration before alerting.')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_data', to='accounts.company')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='monitoring.server')),
            ],
            options={
                'unique_together': {('server', 'metric_type')},
            },
        ),
    ]
