# Generated by Django 6.0.2 on 2026-03-05 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='log_level',
            field=models.CharField(default='INFO', help_text='Agent logging level.', max_length=20),
        ),
        migrations.AddField(
            model_name='server',
            name='telemetry_cadence',
            field=models.PositiveIntegerField(default=30, help_text='Push frequency in seconds.'),
        ),
    ]
