# Generated by Django 6.0.2 on 2026-03-10 00:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_server_log_level_server_telemetry_cadence'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('severity', models.CharField(choices=[('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], db_index=True, default='ERROR', max_length=20)),
                ('context', models.JSONField(blank=True, default=dict, help_text='Contextual metadata for the event.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'System Event',
                'verbose_name_plural': 'System Events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='alertrule',
            name='notification_target',
            field=models.CharField(blank=True, help_text='The email address or Webhook URL to send the alert to.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='notification_type',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('WEBHOOK', 'Webhook')], default='EMAIL', help_text='The strategy used to dispatch notifications.', max_length=10),
        ),
    ]
